hiren/urls.py
from django.conf.urls import url, include
from django.conf import settings
from recipe import views
from django.contrib.auth.views import logout
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^create/', views.create, name='create'),
    url(r'^cuisine/(?P<cuisine>[^\.]+)/', views.cuisine),
    url(r'^meal/(?P<meal>[^\.]+)/', views.meal),
    url(r"^recipes/(?P<pk>[^\.]+)/edit/$", views.recipe_edit, name='recipe_edit'),
    url(r"^recipes/(?P<pk>[^\.]+)/delete/$", views.delete),
    url(r"^recipes/(?P<pk>[^\.]+)/cook/$", views.cooked, name='cooked_at'),
    url(r"^recipes/(?P<pk>[^\.]+)/$", views.recipe),
    url(r'^recipes/', views.recipes, name='recipes'),
    url(r'^recent/', views.recent, name='recent'),
    url(r'^logout/', logout, {'next_page': '/'}, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
]

recipe/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Recipe(models.Model):
    name = models.CharField(max_length=800, unique=True)
    image = models.ImageField(upload_to='hiren')
    image_thumbnail = ImageSpecField(source='image',
                                     processors=[ResizeToFill(500, 350)],
                                     format='JPEG',
                                     options={'quality': 90})
    image_list = ImageSpecField(source='image',
                                processors=[ResizeToFill(363, 241)],
                                format='JPEG',
                                options={'quality': 70})

    preparation_time = models.CharField(max_length=50, null=True, blank=True)
    cooking_time = models.CharField(max_length=50, null=True, blank=True)
    cuisine_type = (
        ('Ame', 'American'),
        ('Chi', 'Chinese'),
        ('Ind', 'Indian'),
        ('Ita', 'Italian'),
        ('Fre', 'French'),
        ('Gre', 'Greek'),
        ('Med', 'Mediterranean'),
        ('Mex', 'Mexican'),
        ('Nor', 'Nordic'),
        ('Tur', 'Turkish'),
        ('Ban', 'Bangladesh'),
        ('Oth', 'Other'),
    )
    cuisine = models.CharField(max_length=3, choices=cuisine_type, default='Oth')
    meal_type = (
        ('Mai', 'Main Course'),
        ('Sna', 'Snacks'),
        ('Bre', 'Breakfast'),
        ('Sid', 'Side Dishes'),
        ('Des', 'Dessert'),
        ('Cak', 'Cake and Baking'),
        ('Dri', 'Drinks'),
        ('Oth', 'Other')
    )
    meal = models.CharField(max_length=3, choices=meal_type, default='Oth')
    video = models.URLField(null=True, blank=True)
    site = models.URLField(null=True, blank=True)
    ingredient = models.TextField(null=True, blank=True)
    direction = models.TextField(null=True, blank=True)
    tips = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class CookedAt(models.Model):
    date = models.DateTimeField()
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

recipe/forms.py
from django.forms import ModelForm
from .models import Recipe, CookedAt


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = "__all__"


class CookedAtForm(ModelForm):
    class Meta:
        model = CookedAt
        exclude = ('recipe',)

recipe/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import CookedAt, Recipe
from .forms import CookedAtForm, RecipeForm
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib import auth
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import logging


def login(request):
    """
    Handles authentication
    :param request:
    :return:
    """
    if request.user.is_authenticated:
        return redirect('recipes')
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)
            return redirect('recipes')
        else:
            messages.error(request, 'Username/Password is not valid!')
            return redirect('/')
    else:
        return render(request, 'login.html', {'title': 'Login'})


@login_required
def create(request):
    """
    Recipe creation
    :param request:
    :return:
    """
    if request.method == 'POST':
        logger = logging.getLogger(__name__)
        recipe_form = RecipeForm(request.POST, request.FILES)
        if recipe_form.is_valid():
            recipe_form.save()
            messages.info(request, 'Recipe Added')
            return redirect('create')
        else:
            messages.error(request, recipe_form.errors)
            logger.info(recipe_form.errors)
            return redirect('create')
    return render(request, 'add.html', {'title': 'Create New Recipe'})


@login_required
def recipes(request):
    """
    Return all recipe with pagination support
    :param request:
    :return:
    """
    recipes = Recipe.objects.order_by('-id')
    paginator = Paginator(recipes, 8)
    page = request.GET.get('page')
    try:
        yummy = paginator.page(page)
    except PageNotAnInteger:
        # If yummy is not an integer, deliver first page.
        yummy = paginator.page(1)
    except EmptyPage:
        yummy = paginator.page(paginator.num_pages)
    return render(request, 'recipes.html', {"recipes": yummy, 'title': 'Recipes'})


@login_required
def recipe(request, pk=None):
    """
    Serve recipe
    :param request: 
    :param pk: 
    :return: 
    """
    recipe = get_object_or_404(Recipe, pk=pk)
    counter = CookedAt.objects.filter(recipe=recipe).count()
    history = CookedAt.objects.filter(pk=pk)
    return render(request, 'recipe.html', {'recipe': recipe, 'title': recipe.name,
                                           'counter': counter, 'history': history})


@login_required
def recipe_edit(request, pk=None):
    """
    Update recipe
    :param request: 
    :param pk: 
    :return: 
    """
    recipe = get_object_or_404(Recipe, pk=pk)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            form.save()
            messages.info(request, "Recipe updated!")
        else:
            messages.error(request, form.errors)
        return redirect('/recipes/' + pk + '/')
    return render(request, 'recipe_edit.html', {'recipe': recipe, 'title': recipe.name})


@login_required
def cooked(request, pk=None):
    """
    Add cooking date with rating
    :param request: 
    :param pk: 
    :return: 
    """
    if request.method == 'POST':
        form = CookedAtForm(request.POST)
        if form.is_valid():
            validated_form = form.save(commit=False)
            recipe = Recipe.objects.get(pk=pk)
            validated_form.recipe = recipe
            validated_form.save()
            messages.info(request, "Cooking date added!")
        else:
            messages.error(request, form.errors)
        return redirect('/recipes/' + pk + '/cook/')
    return render(request, 'cookedAt.html', {'title': 'Cooking Time and Rating', 'recipe_id': pk})


@login_required
def delete(request, pk=None):
    """
    Delete recipe
    :param request: 
    :param pk: 
    :return: 
    """
    Recipe.objects.filter(pk=pk).delete()
    messages.info(request, "Recipe Deleted!")
    return redirect(recipes)


@login_required
def meal(request, meal=None):
    """
    Serve meal by type
    :param request: 
    :param meal: 
    :return: 
    """
    hiren = Recipe.objects.filter(meal=meal)
    return render(request, 'recipes.html', {"recipes": hiren, 'title': 'Recipes'})


@login_required
def cuisine(request, cuisine=None):
    """
    Serve cuisine by type
    :param request: 
    :param cuisine: 
    :return: 
    """
    hiren = Recipe.objects.filter(cuisine=cuisine)
    return render(request, 'recipes.html', {"recipes": hiren, 'title': 'Recipes'})


@login_required
def recent(request):
    history = CookedAt.objects.distinct().order_by('-id')[:20]
    return render(request, 'recent.html', {"recipes": history, 'title': 'Recently Cooked'})

templates/add.html
{% extends "base.html" %}
{% block content %}

<form method="post" action="{% url 'create' %}" class="form-horizontal" id="form" enctype="multipart/form-data"> {% csrf_token %}
        {% if messages %}
              <div class="alert alert-warning" role="alert">
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
              </div>
        {% endif %}
        <div class="form-group" >
            <label class="control-label col-sm-2" >Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="name" required placeholder="Name of the recipe"/>
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2" >Recipe Image</label>
            <div class="col-sm-10">
                <input type="file" accept="image/*" name="image" required/>
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Preparation Time</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="preparation_time" placeholder="Optional preparation time" />
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Cooking Time</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="cooking_time" placeholder="Optional cooking time" />
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Cuisine Type</label>
            <div class="col-sm-10">
                <select name="cuisine" required>
                    <option value="Ame">American</option>
                    <option value="Chi">Chinese</option>
                    <option value="Ind">Indian</option>
                    <option value="Ita">Italian</option>
                    <option value="Fre">French</option>
                    <option value="Gre">Greek</option>
                    <option value="Med">Mediterranean</option>
                    <option value="Mex">Mexican</option>
                    <option value="Nor">Nordic</option>
                    <option value="Tur">Turkish</option>
                    <option value="Ban" selected>Bangladeshi</option>
                    <option value="Oth">Other</option>
                </select>
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Meal Type</label>
            <div class="col-sm-10">
                <select name="meal" required>
                    <option value="Mai">Main Course</option>
                    <option value="Sna">Snacks</option>
                    <option value="Bre">Breakfast</option>
                    <option value="Sid">Side Dishes</option>
                    <option value="Des">Dessert</option>
                    <option value="Cak">Cake and Baking</option>
                    <option value="Dri">Drinks</option>
                    <option value="Oth">Other</option>
                </select>
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Video Url</label>
            <div class="col-sm-10">
                <input type="url" class="form-control" name="video" placeholder="Optional video URL" />
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Main Site Url</label>
            <div class="col-sm-10">
                <input type="url" class="form-control" name="site" placeholder="Optional main site URL" />
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Ingredient</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="ingredient" placeholder="List of Ingredient" ></textarea>
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Direction</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="direction" placeholder="Direction" ></textarea>
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Tips</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="tips" placeholder="Optional tips" ></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default"><i class="fa fa-save" ></i> Create Recipe</button>
            </div>
        </div>
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{ "Hiren-Recipe: " |add:title | default:"Hiren-Recipe" }}</title>
    {% load staticfiles %}
    <link rel="icon" href="{% static 'favicon.ico' %}">
    {% load compress %}
    {% compress css %}
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/simple-sidebar.css' %}" rel="stylesheet">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/froala_editor.pkgd.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/froala_style.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">
    {% endcompress %}
</head>
<body>
<nav class="navbar navbar-default no-margin navbar-fixed-top">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header fixed-brand">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"  id="menu-toggle">
            <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
        </button>
        <a class="navbar-brand" href="#"><i class="fa fa-heart fa-4"></i> Hiren-Recipe</a>
    </div><!-- navbar-header-->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="active" ><button class="navbar-toggle collapse in" data-toggle="collapse" id="menu-toggle-2"> <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span></button></li>
        </ul>
    </div><!-- bs-example-navbar-collapse-1 -->
</nav>
<div id="wrapper">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav nav-pills nav-stacked" id="menu">

            <li>
                <a href="{% url 'recipes' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-cutlery fa-stack-1x "></i></span> Recipes</a>
            </li>
            <li>
                <a href="{% url 'recent' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span> Recent</a>
            </li>
            <li>
                <a href="{% url 'create' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-plus-circle fa-stack-1x "></i></span>Create New Recipe</a>
            </li>
            <li>
                <a href="{% url 'logout' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-sign-out fa-stack-1x "></i></span>Logout</a>
            </li>
        </ul>
    </div><!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid xyz">
            <div class="row">
                <div class="col-lg-12">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->
</div>
<!-- /#wrapper -->
<!-- jQuery -->
{% compress js %}
<script src="{% static '/js/jquery-1.11.2.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
<script src="{% static '/js/sidebar.js' %}"></script>
<script src="{% static '/js/froala_editor.pkgd.min.js' %}"></script>
<script src="{% static '/js/masonry.pkgd.min.js' %}"></script>
<script src="{% static '/js/bootstrap-datepicker.min.js' %}"></script>
<script>
    $(function() { $('textarea').froalaEditor() });
    $('.grid').masonry({
        itemSelector: '.grid-item',
        columnWidth: 100
    });
</script>
{% endcompress %}
</body>
</html>

templates/cookedAt.html
{% extends "base.html" %}
{% block content %}

<div class="containe">
    <div class="ro">
        {% if messages %}
        <div class="alert alert-warning" role="alert">
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <form method="post" action="{% url 'cooked_at' pk=recipe_id %}" class="form-horizontal"> {% csrf_token %}
            <div class="form-group" >
                <label class="control-label col-sm-2" >Cooked At</label>
                <div class="col-sm-10">
                    <div class="input-group date" data-provide="datepicker">
                        <input type="text" name="date" class="form-control" required>
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group" >
                <label class="control-label col-sm-2">Rating</label>
                <div class="col-sm-10">
                    <select name="rating" required>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default"><i class="fa fa-save" ></i> Save</button>
            </div>
        </div>
        </form>
    </div>
</div>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hiren-Recipe: Login</title>
    {% load staticfiles %}
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}" />


<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
  _paq.push(["setCookieDomain", "*.recipes.pyprism.me"]);
  _paq.push(["setDomains", ["*.recipes.pyprism.me"]]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//bunny.pyprism.me/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '4']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//bunny.pyprism.me/piwik.php?idsite=4&rec=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->


</head>
<body>



<form action="{% url 'login' %}" method="post"> {% csrf_token %}
    {% if messages %}
              <div class="alert alert-info" role="alert">
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
              </div>
            {% endif %}
  <label>
    <input type="text" required name="username" autofocus/>
    <div class="label-text">User name</div>
  </label>
  <label>
    <input type="password" required name="password"/>
    <div class="label-text">Password</div>
  </label>
  <button class="button" type="submit" value="Login" > Login </button>
</form>

</body>
</html>

templates/recent.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        {% if messages %}
              <div class="alert alert-warning" role="alert">
                <ul class="messages">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
              </div>
        {% endif %}
        <div class="col-sm-10 col-sm-offest-1">
            <div class="grid">
                {% for recipe in recipes %}
                <div class="grid-item">
                    <div class="card-container manual-flip">
                        <div class="card">
                            <div class="front">
                                <div class="cover">
                                    <a href="/recipes/{{recipe.recipe.id}}/" ><img src="{{ recipe.recipe.image_list.url }}"/></a>
                                </div>
                                <div class="content">
                                    <div class="main">
                                        <a href="/recipes/{{recipe.recipe.id}}/" ><h3 class="name">{{ recipe.recipe.name }}</h3></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/recipe.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        {% if messages %}
              <div class="alert alert-warning" role="alert">
                <ul class="messages">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
              </div>
        {% endif %}
        <div class="col-md-2 col-md-offset-3">
            <img src="{{ recipe.image_thumbnail.url }}"/>
            <h2 class="text-nowrap">{{ recipe.name }}</h2>
        </div>
    </div>
</div>
<div>
    {% if recipe.preparation_time %}
    <h4 class="text-nowrap">Preparation Time: {{ recipe.preparation_time }}</h4>
    <h4 class="text-nowrap">Cooking Time: {{ recipe.cooking_time }}</h4>
    {% endif %}
    <h4 class="text-nowrap"> Cuisine Style: <a href="/cuisine/{{ recipe.cuisine }}/">{{ recipe.get_cuisine_display }}</a></h4>
    <h4 class="text-nowrap">Meal Type: <a href="/meal/{{ recipe.meal }}/">{{ recipe.get_meal_display }} </a></h4>
    <h4 class="text-nowrap">Number of times cooked: {{ counter }}</h4>
    {% if recipe.video %}
    <a href="{{recipe.video}}" target="_blank"><i class="fa fa-file-video-o" aria-hidden="true"></i> Video </a>
    {% endif %}
    {% if recipe.site %}
    <a href="{{recipe.site}}" target="_blank"><i class="fa fa-link" aria-hidden="true"></i> Site </a>
    {% endif %}
    <hr/>
    {% if recipe.ingredient %}
    <h3 class="text-nowrap"><i class="fa fa-list-ul" aria-hidden="true"></i> Ingredients: </h3>
    <p> {{ recipe.ingredient|safe }} </p>
    {% endif %}
    {% if recipe.direction %}
    <h3><i class="fa fa-arrow-down" aria-hidden="true"></i> Direction: </h3>
    <hr/>
    <p> {{ recipe.direction|safe }} </p>
    <hr/>
    {% endif %}
    {% if recipe.tips %}
    <h3 class="text-nowrap"><i class="fa fa-commenting" aria-hidden="true"></i> Tips: </h3>
    <p> {{ recipe.tips|safe }} </p>
    {% endif %}
    <div class="btn-group">
        <a href="cook/" class="btn btn-block btn-info"><i class="fa fa-cutlery" aria-hidden="true"></i> Lets Cook!</a>
        <a href="edit/" class="btn btn-block btn-warning"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</a>
        <a href="delete/" class="btn btn-block btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</a>
    </div>
    {% if history.exists %}
    <hr/>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th>Date</th>
            <th>Rating</th>
        </tr>
        </thead>
        <tbody>
        {% for i in history %}
        <tr>
            <td>
                {{ i.date }}
            </td>
            <td>
                {{ i.rating }}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock %}

templates/recipe_edit.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="{% url 'recipe_edit' pk=recipe.id %}" class="form-horizontal" id="form" enctype="multipart/form-data"> {% csrf_token %}
        {% if messages %}
              <div class="alert alert-warning" role="alert">
                <ul class="messages">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
              </div>
        {% endif %}
        <div class="form-group" >
            <label class="control-label col-sm-2" >Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" value="{{recipe.name}}" name="name" required placeholder="Name of the recipe"/>
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2" >Recipe Image</label>
            <div class="col-sm-10">
                <input type="file" accept="image/*" name="image" />
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Preparation Time</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="preparation_time" value="{{ recipe.preparation_time|default_if_none:"" }}" placeholder="Optional preparation time" />
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Cooking Time</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="cooking_time" value="{{ recipe.cooking_time|default_if_none:"" }}" placeholder="Optional cooking time" />
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Video Url</label>
            <div class="col-sm-10">
                <input type="url" class="form-control" name="video" value="{{ recipe.video|default_if_none:"" }}" placeholder="Optional video URL" />
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Ingredient</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="ingredient" placeholder="List of Ingredient" >{{ recipe.ingredient|default_if_none:"" }}</textarea>
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Direction</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="direction" placeholder="Direction" >{{ recipe.direction|default_if_none:"" }}</textarea>
            </div>
        </div>
        <div class="form-group" >
            <label class="control-label col-sm-2">Tips</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="tips" placeholder="Optional tips" >{{ recipe.tips|default_if_none:"" }}</textarea>
            </div>
        </div>
        <input type="hidden" name="meal" value="{{ recipe.meal }}">
        <input type="hidden" name="cuisine" value="{{ recipe.cuisine }}">
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default"><i class="fa fa-pencil-square-o" ></i> Update Recipe</button>
            </div>
        </div>
</form>
{% endblock %}